name: Node API CI/CD

on:
  push:
    paths:
      - 'back-end/**'
    branches: [master]
  pull_request:
    paths:
      - 'back-end/**'
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
