name: Fullstack CI

on:
  push:
    paths:
      - 'front-end/my-react-app/**'
      - 'back-end/**'
    branches: [master]
  pull_request:
    paths:
      - 'front-end/my-react-app/**'
      - 'back-end/**'
    branches: [master]

jobs:
  backend:
    name: Backend Build, Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

  frontend:
    name: Frontend Build, Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test -- --watchAll=false
